# Importing Library

In [2]:
import pandas as pd
import math
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
import skimage.io
import skimage.feature
import matplotlib.pyplot as plt
#support algorithm for machine learning
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingRegressor


import numpy as np
from sklearn.svm import SVC
from sklearn.ensemble import ExtraTreesClassifier
import cv2 as cv

# Normalization & classifier

In [4]:
def classifier(ExtraTreesCls,x_test):
    y_pred = ExtraTreesCls.predict(x_test)
    print(y_pred, end="")
    if y_pred[len(y_pred)-1] == 0:
        print("aspal -> ")
    elif y_pred[len(y_pred)-1] == 1:
        print("trotoar -> ")

def Normalizer(x_train):
    for column in x_train:
        x_train[column] = (x_train[column] - x_train[column].mean()) / x_train[column].std()
    return x_train

# Read csv file & data Training

In [8]:
data_train = pd.read_csv("tes/new/train5.csv")
X_train = data_train.drop(('class'), axis=1)
Y_train = data_train['class']
x_train_normalized = Normalizer(X_train)
#x_train_normalized.drop(['dissimilarity', 'energy', 'homogeneity','correlation','ASM','Entrophy'], axis=1, inplace=True)
display(x_train_normalized)
#x_train = X_train.values.tolist()
#y_train = Y_train.values.tolist()
#print(x_train_normalized)
ExtraTrees = ExtraTreesClassifier(max_depth=30, n_estimators=320, random_state=4)
ExtraTreesCls = ExtraTrees.fit(x_train_normalized, Y_train)
#cascade = cv.CascadeClassifier('cascade\haarcascade_fullbody.xml')

contrast    energy  homogeneity  correlation  dissimilarity       ASM  \
0    -0.115272 -0.466790    -0.523110     0.739297       0.157466 -0.431544   
1    -0.063456 -0.478149    -0.546540     0.721304       0.207220 -0.435416   
2    -0.039160 -0.481362    -0.550167     0.708548       0.228782 -0.436501   
3    -0.024635 -0.483105    -0.559877     0.695614       0.243868 -0.437087   
4    -0.011902 -0.484321    -0.571100     0.683239       0.258179 -0.437495   
...        ...       ...          ...          ...            ...       ...   
1529 -0.282619 -0.605125    -0.483595     0.867289      -0.029413 -0.474782   
1530 -0.242902 -0.618502    -0.521102     0.861788       0.020583 -0.478511   
1531 -0.284205 -0.594721    -0.481883     0.868865      -0.030740 -0.471826   
1532 -0.279025 -0.589619    -0.466487     0.867827      -0.043728 -0.470360   
1533 -0.397680 -0.495238    -0.234234     0.886434      -0.233476 -0.441133   

      Entrophy  
0     0.304413  
1     0.349229  
2     0.361434  
3     0.361216  
4     0.355549  
...        ...  
1529  0.771163  
1530  0.834660  
1531  0.794010  
1532  0.827731  
1533  0.654791  

[1534 rows x 7 columns]

# Running Camera with Opencv

In [10]:
cam = cv.VideoCapture('Video/trotoar.mp4')
xx = 184
yy = 1623
data = []
analysis = []
number=0
while True:
    isTrue, frame = cam.read()
    if isTrue == False:
        break
    resize = cv.resize(frame, (1080,1920))
    gray = cv.cvtColor(resize, cv.COLOR_BGR2GRAY)
    #print(gray)
    im = gray[yy:yy + 297, xx:xx + 712]
    g = skimage.feature.greycomatrix(im, [1], [0], 256, symmetric=True, normed=True)
    a1 = skimage.feature.greycoprops(g, 'contrast')[0][0]
    a2 = skimage.feature.greycoprops(g, 'energy')[0][0]
    a3 = skimage.feature.greycoprops(g, 'homogeneity')[0][0]
    a4 = skimage.feature.greycoprops(g, 'correlation')[0][0]
    a5 = skimage.feature.greycoprops(g, 'dissimilarity')[0][0]
    a6 = skimage.feature.greycoprops(g, 'ASM')[0][0]
    a7 = skimage.measure.shannon_entropy(g)
    temp = [a1, a2, a3, a4, a5, a6, a7];
    #temp = [a1];
    data.append(temp)
    analysis.append(temp)
    if len(data) == 5:
        x_test = pd.DataFrame(data, columns=['contrast', 'energy','homogeneity', 'correlation', 'dissimilarity', 'ASM', 'Entrophy'])
        #x_test = pd.DataFrame(data, columns=['contrast'])
        x_test_normalized = Normalizer(x_test)
        classifier(ExtraTreesCls, x_test_normalized)
        data.clear()
    cv.imshow('Unfitured video', frame)
    if cv.waitKey(1) == ord('q'):
        break
print(len(gray[0]))
#release the recording device
cam.release()
#destroy the window
cv.destroyAllWindows()

[0 0 0 1 1]trotoar -> 
[1 1 1 0 1]trotoar -> 
[1 1 1 0 1]trotoar -> 
[1 1 1 0 1]trotoar -> 
[0 0 1 1 1]trotoar -> 
[1 1 1 1 1]trotoar -> 
[1 1 1 1 1]trotoar -> 
[1 1 1 1 0]aspal -> 
[1 1 1 0 1]trotoar -> 
[1 1 1 1 1]trotoar -> 
[1 1 1 0 1]trotoar -> 
[1 1 1 0 0]aspal -> 
[1 0 0 0 1]trotoar -> 
[1 0 1 1 1]trotoar -> 
[1 1 1 1 0]aspal -> 
[1 1 1 0 0]aspal -> 
[1 1 0 0 1]trotoar -> 
[1 0 1 1 1]trotoar -> 
[1 1 0 1 0]aspal -> 
[1 1 1 1 1]trotoar -> 
[1 1 1 0 1]trotoar -> 
[1 0 0 1 1]trotoar -> 
[1 0 1 1 1]trotoar -> 
[1 1 1 0 1]trotoar -> 
[1 0 1 0 1]trotoar -> 
[0 0 1 1 1]trotoar -> 
1080


In [ ]:
ya1=[]
ya2=[]
ya3=[]
ya4=[]
ya5=[]
ya6=[]
ya7=[]
indx = []
for idx,x in enumerate(analysis):
    ya1.append(x[0])
    ya2.append(x[1])
    ya3.append(x[2])
    ya4.append(x[3])
    ya5.append(x[4])
    ya6.append(x[5])
    ya7.append(x[6])
    indx.append(idx)

plt.style.use('seaborn')
fig, ax = plt.subplots(figsize=(15,9))
ax.plot(indx, ya1)
#ax.plot(indx, ya2)
#ax.plot(indx, ya3)
#ax.plot(indx, ya4)
#ax.plot(indx, ya5)
#ax.plot(indx, ya6)
#ax.plot(indx, ya7)
plt.show()